# Generated by Django 5.0.6 on 2024-06-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100, unique=True)),
                ('advanceprice', models.BigIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
    ]
